[package]
name = "rozsda_pelda"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rozsda = { path = "../rozsda_proc_macro/" }
